using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Drawing;
using System.Windows.Forms;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
namespace FurZap {
public partial class MainForm {
 sealed class SavedPage {public Control[] Controls;public Hero Hero;public RichTextBox Editor,Log;public string Baseline;public FList Strategies;public Label Applied;public Action Layout;public Point Scroll;public Dictionary<Control,Rectangle> Bounds;public Dictionary<Control,Font> Fonts;public Dictionary<Control,bool> Stretch;}
 readonly Dictionary<string,SavedPage> Pages=new Dictionary<string,SavedPage>();readonly ToolTip Hints=new ToolTip{InitialDelay=600,AutoPopDelay=9000,ReshowDelay=200};double pageSlide=-1;string LastException="";Label ConnectionLabel,HomeStrategy;Form Mini;Label MiniStatus;Dragon MiniPet;bool? WasRunning;string CheckContext="";string SiteStatus="Сайты: проверка не выполнена";
 public void PreviewComfortStep(int step,string dir){
  switch(step){
   case 0:UiZoom=1;Location=Point.Empty;Size=new Size(1190,820);ReloadPage("Главная");break;
   case 1:Screenshot(Path.Combine(dir,"home.png"));break;
   case 2:Page.AutoScrollPosition=new Point(0,700);break;
   case 3:Screenshot(Path.Combine(dir,"home-status.png"));break;
   case 4:Navigate("Стратегии");Page.AutoScrollPosition=new Point(0,350);break;
   case 5:Screenshot(Path.Combine(dir,"strategies.png"));break;
   case 6:Navigate("Настройки");Page.AutoScrollPosition=new Point(0,1000);break;
   case 7:Screenshot(Path.Combine(dir,"settings.png"));break;
   case 8:ShowMini();break;
   case 9:using(var bmp=new Bitmap(Mini.ClientSize.Width,Mini.ClientSize.Height)){using(var g=Graphics.FromImage(bmp))g.CopyFromScreen(Mini.PointToScreen(Point.Empty),Point.Empty,Mini.ClientSize);bmp.Save(Path.Combine(dir,"compact.png"));}Mini.Close();break;
   case 10:Location=Point.Empty;Size=new Size(1920,1080);UiZoom=2;ReloadPage("Настройки");break;
   case 11:Screenshot(Path.Combine(dir,"settings-200.png"));break;
   case 12:Close();break;
  }
 }
 void SavePage(){if(Subtitle.Text.Length==0||Page.Controls.Count==0)return;Pages[Subtitle.Text]=new SavedPage{Controls=Page.Controls.Cast<Control>().ToArray(),Hero=HeroBox,Editor=ListEditor,Log=LogView,Baseline=ListBaseline,Strategies=StrategyList,Applied=AppliedLabel,Layout=HomeLayout,Scroll=Page.AutoScrollPosition,Bounds=PageBounds,Fonts=PageFonts,Stretch=PageStretch};Page.AutoScrollPosition=Point.Empty;}
 bool RestorePage(string name){SavedPage p;if(!Pages.TryGetValue(name,out p))return false;Page.Controls.AddRange(p.Controls);HeroBox=p.Hero;ListEditor=p.Editor;ListBaseline=p.Baseline;LogView=p.Log;StrategyList=p.Strategies;AppliedLabel=p.Applied;HomeLayout=p.Layout;PageBounds=p.Bounds;PageFonts=p.Fonts;PageStretch=p.Stretch;if(StrategyList!=null){StrategyList.Applied=Selected;StrategyList.Invalidate();}if(AppliedLabel!=null)AppliedLabel.Text="✓ Выбрано: "+Path.GetFileNameWithoutExtension(Selected);if(LogView!=null)LogView.Text=Journal.ToString();return true;}
 void RestoreScroll(string name){SavedPage p;if(Pages.TryGetValue(name,out p))Page.AutoScrollPosition=new Point(-p.Scroll.X,-p.Scroll.Y);}
 bool HasUnsavedLists(){if(Dirty)return true;SavedPage p;return Subtitle.Text!="Списки"&&Pages.TryGetValue("Списки",out p)&&p.Editor!=null&&ListDocument.Changed(p.Baseline,p.Editor.Text);}
 void ReloadPage(string name){if(Busy)return;SavePage();foreach(var key in Pages.Keys.ToArray()){var p=Pages[key];if(p.Editor!=null&&ListDocument.Changed(p.Baseline,p.Editor.Text))continue;foreach(var c in p.Controls)c.Dispose();Pages.Remove(key);}Page.Controls.Clear();Subtitle.Text="";Navigate(name);}
 void AnimatePage(double now){if(pageSlide<0||Page==null)return;Page.Top=0;pageSlide=-1;}
 void DisposeComfort(){if(Mini!=null&&!Mini.IsDisposed)Mini.Dispose();foreach(var p in Pages.Values)foreach(var c in p.Controls)if(c.Parent!=Page&&!c.IsDisposed)c.Dispose();Pages.Clear();Hints.Dispose();}
 void AddHints(Control c){foreach(Control x in c.Controls){if(x is FButton||x is FToggle||x is FCombo)Hints.SetToolTip(x,x.AccessibleName??x.Text);AddHints(x);}}
 string RuntimeContext(){return Selected+"|"+B.ActiveStrategy+"|"+B.Running+"|"+B.ServiceState();}
 void InvalidateChecks(){CheckContext="";SiteStatus="Сайты: требуется повторная проверка";}
 void RecordChecks(ProbeResult[] results){CheckContext=RuntimeContext();SiteStatus="Сайты: "+results.Count(x=>x.Ok)+"/"+results.Length+" доступны · "+DateTime.Now.ToString("HH:mm");if(B.Running)SaveStrategyResult(B.ActiveStrategy,results);B.Pref["last-check-time"]=DateTime.Now.ToString("yyyy-MM-dd HH:mm");B.SavePrefs();}
 void SaveStrategyResult(string strategy,ProbeResult[] results){if(!B.Strategies.Contains(strategy))return;B.Pref["result."+strategy]=DateTime.Now.ToString("yyyy-MM-dd HH:mm")+" · "+results.Count(x=>x.Ok)+"/"+results.Length+" HTTPS";B.SavePrefs();}
 void RefreshComfort(){if(HomeStrategy!=null&&!HomeStrategy.IsDisposed)HomeStrategy.Text=Path.GetFileNameWithoutExtension(Selected)+" · "+B.Strategies.Length+" вариантов в сборке";bool running=B.Running||B.ServiceState()==4;if(WasRunning.HasValue&&WasRunning.Value!=running){if(running){SidebarPet.React();if(HeroBox!=null)HeroBox.Pet.React();}else{SidebarPet.Rest();if(HeroBox!=null)HeroBox.Pet.Rest();}}WasRunning=running;if(CheckContext.Length>0&&CheckContext!=RuntimeContext())InvalidateChecks();if(ConnectionLabel!=null&&!ConnectionLabel.IsDisposed)ConnectionLabel.Text=SiteStatus+"\nГолос и видео: требуется ручная проверка";if(MiniStatus!=null&&!MiniStatus.IsDisposed)MiniStatus.Text=(running?"Движок запущен":"Движок остановлен")+"\n"+System.IO.Path.GetFileNameWithoutExtension(Selected)+"\n"+SiteStatus;if(MiniPet!=null&&!MiniPet.IsDisposed){MiniPet.Sleeping=!running;MiniPet.Checking=Scanning;MiniPet.Reduced=!Motion.Enabled;MiniPet.Advance(Motion.Now);}}
 void ApplyPetSettings(){string mode=B.Get("pet","normal");foreach(var pet in new[]{SidebarPet,HeroBox==null?null:HeroBox.Pet,MiniPet})if(pet!=null&&!pet.IsDisposed){pet.Visible=mode!="hidden";pet.Calm=B.Get("pet-calm","yes")=="yes";pet.SpriteScale=mode=="small"?.72f:1;}}
 void ComfortSettings(){var c=Box(1150,174);Title(c,"Твой дракон","Спокойное ожидание и размер персонажа.");var size=Combo(c,new[]{"Обычный","Маленький","Скрыть"},23,103,230);string[] values={"normal","small","hidden"};size.SelectedIndex=Math.Max(0,Array.IndexOf(values,B.Get("pet","normal")));size.SelectedIndexChanged+=(s,e)=>{B.Pref["pet"]=values[size.SelectedIndex];B.SavePrefs();ApplyPetSettings();};Check(c,"Спокойные реакции без прыжков",285,107,B.Get("pet-calm","yes")=="yes",v=>{B.Pref["pet-calm"]=v?"yes":"no";B.SavePrefs();ApplyPetSettings();});}
 void StrategyExtras(FList list,Action fill){var c=Box(515,226);Title(c,"Твои отметки","Избранные сверху. Затем — недавно выбранные. Проверки привязаны ко времени.");var meta=L(c,"",23,85,710,28,10);var note=Input(c,"",23,122,440);var favorite=Btn(c,"В избранное",478,122,224,35,()=>{if(list.SelectedItem==null)return;string key="favorite."+list.SelectedItem;B.Pref[key]=B.Get(key)=="yes"?"no":"yes";B.SavePrefs();fill();});Btn(c,"Сохранить заметку",23,173,245,35,()=>{if(list.SelectedItem==null)return;B.Pref["note."+list.SelectedItem]=Convert.ToBase64String(Encoding.UTF8.GetBytes(note.Text));B.SavePrefs();Feedback("Заметка сохранена",list.SelectedItem.ToString());});Action refresh=()=>{if(list.SelectedItem==null)return;string strategy=list.SelectedItem.ToString();favorite.Text=B.Get("favorite."+strategy)=="yes"?"★ В избранном":"☆ В избранное";try{note.Text=Encoding.UTF8.GetString(Convert.FromBase64String(B.Get("note."+strategy)));}catch{note.Text="";}meta.Text=B.Get("result."+strategy,"Для этой стратегии нет результатов проверки");};list.SelectedIndexChanged+=(s,e)=>refresh();refresh();}
 void RestoreWorking(){string path=B.Working();if(path==null)throw new Exception("Сначала отметь рабочую конфигурацию в разделе «Профили».");string strategy=File.ReadAllText(Path.Combine(path,"strategy.txt"));if(Confirm("Вернуть "+strategy+"?\n"+B.Description(path)+"\nПоследняя проверка: "+B.Get("result."+strategy,"нет отметки")+"\nТекущая конфигурация будет сохранена в истории."))Work(()=>B.ApplySnapshot(path),SyncProfile);}
 Card ComfortHome(){var c=Box(679,188);Title(c,"Подключение и восстановление","Состояние процесса и доступность сайтов проверяются отдельно.");ConnectionLabel=L(c,SiteStatus+"\nГолос и видео: требуется ручная проверка",23,80,700,45,10);Btn(c,"Вернуть рабочую",23,137,240,36,RestoreWorking);Btn(c,"Компактное окно",280,137,240,36,ShowMini);Btn(c,"Проверки",535,137,180,36,()=>Navigate("Проверки"));return c;}
 void ShowMini(){if(Mini!=null&&!Mini.IsDisposed){Mini.Show();Mini.Activate();Hide();return;}Mini=new Form{Text="FurZap · компактный",ClientSize=new Size(520,245),MinimumSize=new Size(536,284),BackColor=Theme.Bg,ForeColor=Theme.Text,StartPosition=FormStartPosition.CenterScreen,Icon=Icon};MiniStatus=L(Mini,"",22,20,350,83,11,true);MiniPet=new Dragon{Bounds=new Rectangle(375,14,122,117),Calm=true};Mini.Controls.Add(MiniPet);Btn(Mini,"Запустить",22,122,150,40,()=>Work(()=>{if(B.ServiceState()!=0)B.ServiceStart();else B.Start(Selected);}));Btn(Mini,"Остановить",184,122,150,40,()=>Work(()=>{B.Stop();if(B.ServiceState()!=0)B.ServiceStop();}));Btn(Mini,"Полный интерфейс",22,182,312,40,()=>{Mini.Hide();Restore();});double nextMiniRefresh=0;var timer=new System.Windows.Forms.Timer{Interval=17};timer.Tick+=(s,e)=>{if(Mini.Visible&&Mini.WindowState!=FormWindowState.Minimized){MiniPet.Advance(Motion.Now);if(Motion.Now>=nextMiniRefresh){nextMiniRefresh=Motion.Now+2;RefreshComfort();}}};Mini.Shown+=(s,e)=>timer.Start();Mini.FormClosing+=(s,e)=>{timer.Dispose();Restore();};Mini.Disposed+=(s,e)=>timer.Dispose();RefreshComfort();ApplyPetSettings();Mini.Show();Hide();}
 public static string RedactReport(string text,string user,string root){foreach(string value in new[]{root,Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)})if(!String.IsNullOrEmpty(value))text=text.Replace(value,"[папка]");if(!String.IsNullOrEmpty(user))text=text.Replace(user,"[пользователь]");text=Regex.Replace(text,@"(?i)(authorization|token|password|secret|api[_-]?key)\s*[:=]\s*\S+","$1=[скрыто]");text=Regex.Replace(text,@"[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}","[email]");text=Regex.Replace(text,@"\b(?:\d{1,3}\.){3}\d{1,3}\b","[IP]");text=Regex.Replace(text,@"(?i)\b[0-9a-f]{0,4}:(?:[0-9a-f:]+:)[0-9a-f:]*\b","[IPv6]");text=Regex.Replace(text,@"https?://[^\s]+","[URL]");return text;}
 void ShowErrorReport(){string report="FurZap "+typeof(MainForm).Assembly.GetName().Version+"\nWindows/runtime: "+Environment.OSVersion+" / "+Environment.Version+"\nРаздел: "+Subtitle.Text+"\nСтратегия: "+Selected+"\n\nПоследняя ошибка:\n"+LastException+"\n\nСобытия:\n"+Journal;report=RedactReport(report,Environment.UserName,Path.GetFullPath(B.Root));TextDialog("Отчёт — проверь и удали личные данные перед сохранением",report,true,value=>{using(var dialog=new SaveFileDialog{FileName="FurZap-report.txt",Filter="Текст|*.txt"})if(dialog.ShowDialog(this)==DialogResult.OK)File.WriteAllText(dialog.FileName,value,Encoding.UTF8);});}
 void UpdateCard(){var c=Box(785,148);Title(c,"Обновления FurZap","Новая версия, список изменений и проверка SHA-256 перед установкой.");Btn(c,"Проверить FurZap",23,93,260,36,CheckAppUpdate,true);Btn(c,"Отчёт об ошибке",298,93,240,36,ShowErrorReport);}
 async void CheckAppUpdate(){if(Busy||B.Preview)return;Busy=true;var updateButton=ActionButton;string updateText=updateButton==null?null:updateButton.Text;if(updateButton!=null)updateButton.Text="Проверяю…";try{var release=await Task.Run(()=>AppUpdater.Latest());if(release.Version<=typeof(MainForm).Assembly.GetName().Version){Feedback("Обновлений нет","Установлена актуальная версия.");return;}if(!Confirm("Доступна версия "+release.Version+"\n\n"+release.Notes+"\n\nСкачать обновление?"))return;using(var dialog=new Form{Text="Загрузка FurZap",ClientSize=new Size(440,160),StartPosition=FormStartPosition.CenterParent,BackColor=Theme.Bg})using(var cancel=new CancellationTokenSource()){var bar=new ProgressBar{Bounds=new Rectangle(24,28,390,25)};dialog.Controls.Add(bar);var label=L(dialog,"Загрузка…",24,62,390,25);var abort=new FButton{Text="Отменить",Bounds=new Rectangle(24,102,180,36)};abort.Click+=(s,e)=>cancel.Cancel();dialog.Controls.Add(abort);dialog.FormClosing+=(s,e)=>cancel.Cancel();dialog.Show(this);string staged=await Task.Run(()=>AppUpdater.Download(release,B.Data,cancel.Token,percent=>UI(()=>{if(!dialog.IsDisposed){bar.Value=percent;label.Text=percent+"%";}})));dialog.Close();if(!Confirm("Архив проверен. Установить FurZap "+release.Version+" и перезапустить приложение?\nОбычный процесс FurZap будет остановлен. Служба продолжит работать. Настройки и списки сохранятся."))return;if(HasUnsavedLists()){MessageBox.Show(this,"Сначала сохрани список и повтори обновление.");return;}B.Stop();AppUpdater.LaunchInstaller(staged);Busy=false;AllowExit=true;Close();}}catch(OperationCanceledException){Feedback("Загрузка отменена","Приложение не изменено.");}catch(Exception ex){Error(ex);}finally{Busy=false;if(updateButton!=null&&!updateButton.IsDisposed)updateButton.Text=updateText;}}
}
}
