using System;
using System.IO;
using System.Linq;
using System.Drawing;
using System.Windows.Forms;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
namespace FurZap {
public partial class MainForm {
 CancellationTokenSource ScanCancel;List<StrategyResult> ScanResults=new List<StrategyResult>();float UiZoom=1;bool Scanning;
 Dictionary<Control,Rectangle> HomeBase=new Dictionary<Control,Rectangle>();Dictionary<Control,Font> BaseFonts=new Dictionary<Control,Font>();
 int ContentWidth{get{return Math.Max(815,(int)(Page.Parent.ClientSize.Width/RenderZoom));}}
 static Color AccentColor(string key){return key=="cyan"?Color.FromArgb(94,218,218):key=="purple"?Color.FromArgb(193,151,255):Color.FromArgb(255,164,94);}
 void InitializeExtras(){float zoom;if(float.TryParse(B.Get("zoom","100"),out zoom))UiZoom=Math.Max(1,Math.Min(2f,zoom/100));if(B.Get("compact","no")=="yes"){Side.Width=178;foreach(var n in Nav)n.Width=144;Size=new Size(1050,740);SidebarPet.Visible=false;}Tray.ContextMenuStrip.Opening+=(s,e)=>BuildTray();SidebarPet.MouseEnter+=(s,e)=>SidebarPet.React();}
 void BuildTray(){var menu=Tray.ContextMenuStrip;menu.Items.Clear();bool running=B.Running||B.ServiceState()==4;var status=menu.Items.Add(running?"● Движок работает":"○ Движок остановлен");status.Enabled=false;menu.Items.Add("Открыть FurZap",null,(s,e)=>Restore());menu.Items.Add("Компактное окно",null,(s,e)=>ShowMini());var start=menu.Items.Add("Запустить",null,(s,e)=>Work(()=>{if(B.ServiceState()!=0)B.ServiceStart();else B.Start(Selected);}));start.Enabled=!Busy&&!running;var stop=menu.Items.Add("Остановить",null,(s,e)=>Work(()=>{B.Stop();if(B.ServiceState()!=0)B.ServiceStop();}));stop.Enabled=!Busy&&running;var profiles=new ToolStripMenuItem("Профиль");foreach(string name in B.Profiles()){string chosen=name;profiles.DropDownItems.Add(chosen,null,(s,e)=>Work(()=>B.ApplyProfile(chosen),SyncProfile));}profiles.Enabled=!Busy&&profiles.DropDownItems.Count>0;menu.Items.Add(profiles);menu.Items.Add("Выход",null,(s,e)=>{AllowExit=true;Close();});}
 void RefreshExtras(){bool running=B.Running||B.ServiceState()==4;Tray.Text="FurZap · "+(Scanning?"проверка сети":running?"движок работает":"движок остановлен");ApplyPetSettings();SidebarPet.Sleeping=!running&&!Scanning;SidebarPet.Checking=Scanning;if(HeroBox!=null&&!HeroBox.IsDisposed){HeroBox.Pet.Sleeping=!running&&!Scanning;HeroBox.Pet.Checking=Scanning;}}
 void SyncProfile(){Selected=B.Get("strategy",Selected);ReloadPage(Subtitle.Text);}
 void AppearancePage(){var c=Box(887,245);Title(c,"Внешний вид","Масштаб до 200% подстраивается под ширину окна. Оформление применяется сразу.");var theme=Combo(c,new[]{"Тёплый оранжевый","Бирюзовый","Лавандовый"},23,99,225);string[] themes={"orange","cyan","purple"};theme.SelectedIndex=Math.Max(0,Array.IndexOf(themes,B.Get("theme","orange")));var zoom=Combo(c,new[]{"100%","125%","150%","175%","200%"},270,99,155);zoom.SelectedIndex=Math.Max(0,Array.IndexOf(new[]{"100","125","150","175","200"},B.Get("zoom","100")));var compact=Check(c,"Компактное окно и узкая боковая панель",23,151,B.Get("compact","no")=="yes",v=>{});Btn(c,"Применить оформление",23,193,290,36,()=>{B.Pref["theme"]=themes[theme.SelectedIndex];B.Pref["zoom"]=zoom.Text.TrimEnd(new char[]{'%'});B.Pref["compact"]=compact.Checked?"yes":"no";B.SavePrefs();Theme.Orange=AccentColor(B.Get("theme"));UiZoom=float.Parse(B.Get("zoom"))/100;Side.Width=compact.Checked?178:213;foreach(var n in Nav)n.Width=compact.Checked?144:178;SidebarPet.Visible=!compact.Checked;if(compact.Checked)Size=new Size(1050,740);ReloadPage("Настройки");RepaintTree(this);Feedback("Оформление обновлено","Тема и масштаб сохранены.");},true);}
 void CaptureHome(Control c){HomeBase[c]=c.Bounds;BaseFonts[c]=c.Font;foreach(Control child in c.Controls)CaptureHome(child);}
 void ResetHome(){foreach(var pair in HomeBase)if(!pair.Key.IsDisposed){pair.Key.Anchor=AnchorStyles.Top|AnchorStyles.Left;pair.Key.Bounds=pair.Value;pair.Key.Font=BaseFonts[pair.Key];}}
 Dictionary<Control,Rectangle> PageBounds=new Dictionary<Control,Rectangle>();Dictionary<Control,Font> PageFonts=new Dictionary<Control,Font>();Dictionary<Control,bool> PageStretch=new Dictionary<Control,bool>();
 float RenderZoom{get{return Math.Max(.85f,Math.Min(UiZoom,Page.Parent.ClientSize.Width/815f));}}
 void CaptureScale(Control c,Dictionary<Control,Rectangle> bounds,Dictionary<Control,Font> fonts){bounds[c]=c.Bounds;fonts[c]=c.Font;foreach(Control child in c.Controls)if(!(c is FInput))CaptureScale(child,bounds,fonts);}
 void ScaleStored(Control c,float factor,Dictionary<Control,Rectangle> bounds,Dictionary<Control,Font> fonts,bool page){Rectangle r=bounds[c];if(c.Parent==Page&&c is Label)r.Width=Math.Min(r.Width,ContentWidth-r.X-30);if(page&&c.Parent==Page&&PageStretch[c])r.Width=ContentWidth-(c is Card?61:65);c.Anchor=AnchorStyles.Top|AnchorStyles.Left;c.SetBounds((int)(r.X*factor),(int)(r.Y*factor),(int)(r.Width*factor),(int)(r.Height*factor));Font f=fonts[c];c.Font=new Font(f.FontFamily,f.Size*factor,f.Style);var list=c as FList;if(list!=null)list.RowHeight=(int)(38*factor);var input=c as FInput;if(input!=null)input.SetZoom(factor);foreach(Control child in c.Controls)if(!(c is FInput))ScaleStored(child,factor,bounds,fonts,page);}
 void ScaleHome(params Control[] cards){var bounds=new Dictionary<Control,Rectangle>();var fonts=new Dictionary<Control,Font>();foreach(var c in cards)CaptureScale(c,bounds,fonts);Page.SuspendLayout();try{foreach(var c in cards)ScaleStored(c,RenderZoom,bounds,fonts,false);if(HeroBox!=null)HeroBox.PaintZoom=RenderZoom;}finally{Page.ResumeLayout();}}
 void ApplyPageScale(){if(Subtitle.Text=="Главная")return;PageBounds.Clear();PageFonts.Clear();PageStretch.Clear();foreach(Control c in Page.Controls){PageStretch[c]=(c.Anchor&AnchorStyles.Right)!=0||c is Card||c is FList||c is RichTextBox;CaptureScale(c,PageBounds,PageFonts);}RenderPageScale();}
 void RenderPageScale(){if(Subtitle.Text=="Главная"||PageBounds.Count==0)return;Point scroll=Page.AutoScrollPosition;Page.SuspendLayout();try{Page.AutoScrollPosition=Point.Empty;foreach(Control c in Page.Controls)if(PageBounds.ContainsKey(c))ScaleStored(c,RenderZoom,PageBounds,PageFonts,true);}finally{Page.ResumeLayout();Page.AutoScrollPosition=new Point(-scroll.X,-scroll.Y);}}
 RichTextBox ResultsBox(int y,int h){var r=new RoundedTextBox{Bounds=new Rectangle(32,y,ContentWidth-65,h),BackColor=Theme.Card,ForeColor=Theme.Text,BorderStyle=BorderStyle.None,ReadOnly=true,Font=Theme.F(10),DetectUrls=false,WordWrap=true};Page.Controls.Add(r);return r;}
 void ChecksPage(){
  var info=Box(22,158);Title(info,"Проверка доступности","Discord, YouTube и VRChat: HTTPS-запросы напрямую, без системного прокси.\nСайт и TLS — отдельно от голосовой связи, видео и входа в приложение.");Btn(info,"Проверить сейчас",23,112,220,34,()=>StartChecks(false),true);Btn(info,"Подобрать стратегию",256,112,250,34,()=>StartChecks(true));
  L(Page,"Голос / UDP: не проверено автоматически. Подключись к голосовому каналу\nили миру VRChat и проверь передачу и приём звука с собеседником.",32,195,750,47,10).ForeColor=Theme.Muted;
  var voice=Combo(Page,new[]{"Голос ещё не проверен","Голос работает — проверено мной","Голос не работает — проверено мной"},32,255,510);L(Page,"Ручная отметка для текущей проверки; не участвует в оценке стратегий.",32,299,750,26,9).ForeColor=Theme.Muted;
  var output=ResultsBox(342,100);output.Name="check-output";output.Text=File.Exists(Path.Combine(B.Data,"last-check.txt"))?File.ReadAllText(Path.Combine(B.Data,"last-check.txt")):"Здесь появятся результаты. Время — длительность HTTP-запроса, не игровой пинг.";voice.SelectedIndexChanged+=(s,e)=>{output.AppendText("\n"+DateTime.Now.ToString("HH:mm:ss")+" · "+voice.Text);};
  var progress=L(Page,"Ожидание проверки",33,461,730,26,10);progress.Name="check-progress";
  var cancel=new FButton{Text="Отменить",Bounds=new Rectangle(32,500,180,40),Enabled=false,Name="check-cancel"};cancel.Click+=(s,e)=>{if(ScanCancel!=null){ScanCancel.Cancel();progress.Text="Отмена… возвращаю прежнее состояние";cancel.Enabled=false;}};Page.Controls.Add(cancel);
  var list=new FList{Bounds=new Rectangle(32,563,ContentWidth-65,210),Name="check-list"};Page.Controls.Add(list);FillScanList(list);Btn(Page,"Выбрать результат",32,790,240,42,()=>{if(list.SelectedIndex>=0&&list.SelectedIndex<ScanResults.Count)Choose(ScanResults[list.SelectedIndex].Strategy);},true);Btn(Page,"Подробности",285,790,190,42,()=>{if(list.SelectedIndex>=0&&list.SelectedIndex<ScanResults.Count){var r=ScanResults[list.SelectedIndex];TextDialog(r.Strategy,r.Error+"\r\n"+String.Join("\r\n",r.Checks.Select(x=>x.ToString())),false,null);}});Btn(Page,"Последний отчёт",489,790,215,42,()=>{string p=Path.Combine(B.Data,"last-scan.txt");TextDialog("Отчёт подбора",File.Exists(p)?File.ReadAllText(p):"Подбор ещё не выполнялся.",false,null);});
  L(Page,"Подбор временно переключает стратегии. После завершения или отмены возвращается\nпрежний режим работы. Сортировка: число доступных сайтов, затем время запросов.\nРезультат 3/3 не гарантирует работу видео, голосовой связи и всех сервисов.",32,854,760,74,10).ForeColor=Theme.Muted;
 }
 void FillScanList(FList list){list.Items.Clear();list.Items.AddRange(ScanResults.Select(x=>x.ToString()));list.SelectedIndex=list.Items.Count>0?0:-1;list.Invalidate();}
 async void StartChecks(bool scan){if(Busy)return;if(B.Preview){Feedback("Предпросмотр","Сетевые операции доступны при запуске в Windows.");return;}if(ExternalTool!=null&&!ExternalTool.HasExited)throw new Exception("Сначала закрой исходный менеджер или тесты.");var output=(RichTextBox)Page.Controls["check-output"];var progress=(Label)Page.Controls["check-progress"];var cancel=(FButton)Page.Controls["check-cancel"];var list=(FList)Page.Controls["check-list"];Busy=true;Scanning=true;ScanCancel=new CancellationTokenSource();cancel.Enabled=true;RefreshExtras();output.Text=scan?"Подбор запущен. Не закрывай программу до восстановления прежней конфигурации.":"Проверяю три HTTPS-адреса…";try{if(scan){ScanResults=await Task.Run(()=>B.ScanStrategies(ScanCancel.Token,(done,total,label)=>UI(()=>{progress.Text=done+" / "+total+" · "+label;SidebarPet.React();})));foreach(var result in ScanResults)SaveStrategyResult(result.Strategy,result.Checks);FillScanList(list);output.Text="Подбор завершён. Прежнее состояние восстановлено. Выбери результат, если хочешь сохранить другую стратегию.";}else{var results=await Task.Run(()=>B.ProbeServices(ScanCancel.Token));output.Text=DateTime.Now+"\r\n"+String.Join("\r\n\r\n",results.Select(x=>x.ToString()))+"\r\n\r\nГолос, видео и вход в аккаунт: автоматически не проверены.";Backend.Atomic(Path.Combine(B.Data,"last-check.txt"),output.Text);RecordChecks(results);}progress.Text="Готово";Feedback("Проверка завершена",scan?"Прежний режим работы восстановлен.":"Результаты доступны на этой странице.");}catch(OperationCanceledException){progress.Text="Отменено";output.AppendText(scan?"\nПодбор отменён. Прежнее состояние восстановлено. Частичный отчёт сохранён.":"\nПроверка отменена.");}catch(Exception ex){progress.Text="Не завершено — см. ошибку";Error(ex);}finally{ScanCancel.Dispose();ScanCancel=null;Busy=false;Scanning=false;cancel.Enabled=false;RefreshState();}}
 public void PreviewExtras(int stage){
  noticeUntil=0;Notice.Visible=false;
  if(stage==0){Navigate("Настройки");Page.AutoScrollPosition=new Point(0,600);}
  if(stage==1){foreach(var card in Page.Controls.OfType<Card>())foreach(var toggle in card.Controls.OfType<FToggle>())toggle.Checked=!toggle.Checked;Page.AutoScrollPosition=Point.Empty;}
  if(stage==2)Page.AutoScrollPosition=new Point(0,600);
  if(stage==3){UiZoom=1.5f;Theme.Orange=AccentColor("purple");Location=Point.Empty;Size=new Size(1920,1080);Navigate("Настройки");}
  if(stage==4)Page.AutoScrollPosition=new Point(0,1200);
  if(stage==5)Navigate("Главная");
  if(stage==6){Size=new Size(1190,820);Navigate("Проверки");}
 }
 void ProfilesPage(){
  var c=Box(22,181);Title(c,"Твои профили","Сохраняются стратегия, порты, списки, IPSet и пакеты Discord / Game.\nНазвания «На каждый день», «VRChat», «Другая сеть» можно использовать для своих настроек.");var name=Input(c,"На каждый день",23,116,390);Btn(c,"Сохранить новый",429,114,250,39,()=>{string saved=name.Text;B.SaveProfile(saved);ReloadPage("Профили");Feedback("Профиль сохранён",saved);},true);
  string[] names=B.Profiles();var profiles=Combo(Page,names,32,225,420);Btn(Page,"Применить профиль",470,223,270,40,()=>{if(profiles.SelectedItem!=null){string n=profiles.Text;Work(()=>B.ApplyProfile(n),SyncProfile);}},true);L(Page,"Работающий движок будет перезапущен; остановленный останется остановленным.",32,278,770,28,10).ForeColor=Theme.Muted;
  var h=Box(322,132);Title(h,"История и рабочая точка","Перед изменениями создаётся копия. Рабочую конфигурацию отмечаешь ты после проверки.");Btn(h,"Отметить рабочую",23,84,245,35,()=>{B.MarkWorking();ReloadPage("Профили");Feedback("Рабочая точка сохранена","Можно вернуться к ней одной кнопкой.");});Btn(h,"Вернуть рабочую",282,84,245,35,RestoreWorking);
  string[] history=B.History();var list=new FList{Bounds=new Rectangle(32,475,ContentWidth-65,220)};list.Items.AddRange(history.Select(x=>B.Description(x)));list.SelectedIndex=history.Length>0?0:-1;Page.Controls.Add(list);Btn(Page,"Восстановить из истории",32,716,290,42,()=>{if(list.SelectedIndex>=0){string p=history[list.SelectedIndex];Work(()=>B.ApplySnapshot(p),SyncProfile);}},true);Btn(Page,"Открыть папку копий",335,716,245,42,()=>{string p=Path.Combine(B.Data,"history");Directory.CreateDirectory(p);Open(p);});
 }
}
}
